/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }

    @Test void restaurantConstructor(){
        Restaurant verify = new Restaurant("McDonald's",3,5);
        String actualValue = "McDonald's";
        assertEquals(actualValue,verify.getName());
    }

    @Test void toStringTest(){
        Restaurant toStringRes = new Restaurant("McDonald's",3,5);
        assertEquals("Restaurant{name='McDonald's', stars=5.0, price=3}",String.valueOf(toStringRes));
    }

    @Test void addReviewTest(){
        Restaurant addReviewTesting = new Restaurant("McDonald's",3,5);
        Review reviewTest = new Review("Best Restaurants Ever","Jamal",5 );
        addReviewTesting.addReview(reviewTest);
        assertEquals(addReviewTesting.getRestaurantRate().size(),addReviewTesting.getRestaurantRate().size());
    }

    @Test void testReviewConstructor(){
        Review testRev = new Review("Best Restaurants Ever","Jamal",5);
        String actualValue = testRev.getAuthor();
        assertEquals(actualValue,testRev.getAuthor());
    }

    @Test void testToStringReview(){
        Review reviewTest = new Review("Best Restaurants Ever","Jamal",5);
        assertEquals("Review{body='Best Restaurants Ever', author='Jamal', stars=5}",String.valueOf(reviewTest));


    }
}
